name: Publish Nuget Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
    - name: Push
      run: dotnet nuget push Schig.Blazor.C3js.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${API_KEY}
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY}}
